asynciterable.js
asynciterable/from.js
asynciterable/map.js
asynciterator.js
index.js
internal/isiterable.js

There's still a lot of roughness here.  We'll need to update the subclassing interface to make things more ergonomic, for example.  Also, `from` only converts from synchronous iterables.  We'll of course want to adapt raw async iterables as well.

Add working first implementations of AsyncIterator and AsyncIterable

---

.gitignore
package.json
tsconfig_base.json
tsconfig_commonjs.json
tsconfig_es2015.json
tslint.json

This PR setup initial build scripts, as well as arbitrary configurations. 
**What's included**
1. build scripts
- `build:commonjs` : build CommonJS target
- `build:es2015` : build native ES2015 target
- `build` : run all builds at once. This script does wildcard matching, so any `build:${target}` type script being added in further will be triggered as well.
2. lint script
- `lint:src` : run lint against source code
- `lint` : run lint against all code (in further). as same as build script, it does wildcard matching.
3. update test script
- invoke tape with `ts-node` to allow write test case in typescript.
4. convenient script
- `commit` : run `commitizen`, commit message wizard
- `info` : display currently available script with simple description.
5. lint-staged / husky for commit hook
: …

chore(package): setup initial build scripts

---

src/add/iterable-operators/concatAll.ts

Looks like I typo'd this typing when I added the proto method definition.

fix(typings): Fix IterableX#concatAll typings to accept IterableX<Iterable<T>>

---

src/add/asynciterable-operators/groupby.ts
src/add/iterable-operators/groupby.ts

replacing `source` param with `this` so that the outer iterable is properly composed in prototypal invocations.
resolves #33

fixing missing this in groupby operator prototype signatures

---

spec/asynciterable-operators/groupby-spec.ts
spec/iterable-operators/groupby-spec.ts
src/add/asynciterable-operators/groupby.ts
src/add/iterable-operators/groupby.ts
src/asynciterable/groupby.ts
src/iterable/groupby.ts

This PR adds a new parameter (`resultSelector`) to the end of the parameter list for both async and non-async `groupBy` operators. `resultSelector` allows the operator to project the results to a custom structure rather than using the default `GroupedIterable` or `GroupedAsyncIterable`. By default, if not specified, `resultSelector` simply uses the `groupByResultIdentity` or `groupByResultIdentityAsync` function for projection, which creates the `GroupedIterable` or `GroupedAsyncIterable` instance.
resolves #35

adding resultselector parameter to groupby operators

---

tsconfig/tsconfig.base.json

This is covered by `--strict` option. We don't have to enable it individually.

chore(tsconfig.json): remove needless strictNullChecks option

---

.travis.yml
gulpfile.js
spec/Ix.ts

By not specifying a file extension in package.json's "main" field, node will pick the right mjs or js entries based on whether it's running with `--experimental-modules` set or not.

Fix mjs main

---

readme.md

**Description:** This PR improves the operator import example by fixing a variable name and adding the expected output
before:
after:
fix #69

69 improve operator import example

---

readme.md

This PR ensures that the chain operator example from the docs can be run without encountering `map is not a function` errors in a CommonJS environment.
fix #78

docs(chain-operator): add methods to require statements for chain operator example

---

spec/asynciterable-operators/memoize-spec.ts
spec/asynciterable-operators/publish-spec.ts
spec/asynciterable-operators/share-spec.ts
spec/asynciterable-operators/zip-spec.ts
spec/iterable-operators/memoize-spec.ts
spec/iterable-operators/publish-spec.ts
spec/iterable-operators/share-spec.ts
spec/iterable-operators/zip-spec.ts
src/add/asynciterable-operators/zip.ts
src/add/iterable-operators/zip.ts
src/asynciterable/zip.ts
src/iterable/zip.ts

breaking change: zip selectors now take a single "values" Array argument, instead of varargs

Zip `n` sources

---

src/add/asynciterable-operators/concat.ts
src/add/asynciterable-operators/concatall.ts
src/add/asynciterable-operators/merge.ts
src/add/asynciterable-operators/mergeall.ts
src/add/iterable-operators/concat.ts
src/add/iterable-operators/concatall.ts
src/asynciterable/__modules.ts
src/asynciterable/concat.ts
src/asynciterable/concatall.ts
src/asynciterable/for.ts
src/asynciterable/merge.ts
src/asynciterable/mergeall.ts
src/iterable/__modules.ts
src/iterable/concat.ts
src/iterable/concatall.ts
src/iterable/for.ts

Adds TypeScript overloads for `AsyncIterable` `concat` and `merge`, as well as `Iterable` `concat`.  Also splits files for `concat` and `concatAll`, `merge` and `mergeAll`.

feat(merge/concat): add typed overloads for merge/concat

---

readme.md

Just a small fix :blush: This is based on the `console.log`s above, so it should show that text.

Fix async iterator docs in readme

---

spec/asynciterable/asyncify-spec.ts
spec/asynciterable/asyncifyerrback-spec.ts
src/Ix.ts
src/add/asynciterable/asyncify.ts
src/add/asynciterable/asyncifyerrback.ts
src/asynciterable/__modules.ts
src/asynciterable/asyncify.ts
src/asynciterable/asyncifyerrback.ts
src/asynciterable/fromevent.ts
src/asynciterable/fromeventpattern.ts

Adds the `asyncify` and `asyncifyErrback` to bind to callbacks to support regular callbacks and node style errBack callbacks to be bound to `AsyncIterable`.

feat(asyncify): adds asyncify and asyncifyErrback

---

src/asynciterable/pipe.ts
src/iterable/pipe.ts

`pipe()`'s signature says it always takes `Iterable<T>` as the input and returns `IterableX<T>` as the result. But if `operations` is zero, it returned the input as the result. It's wrong.

fix(pipe): pipe() should always return IterableX<T>

---

src/add/iterable-operators/single.ts

reported in https://github.com/ReactiveX/IxJS/pull/83#issuecomment-341832266

fix(single): make iterable prototype single predicate an optional parameter again

---

spec/asynciterable/as-spec.ts
spec/asynciterable/from-spec.ts
spec/asynciterablehelpers.ts
spec/iterable/as-spec.ts
spec/iterablehelpers.ts
src/asynciterable/asynciterablex.ts
src/iterable/iterablex.ts

This PR introduces `Iterable.as()` and `AsyncIterable.as()` convenience methods to wrap values as Iterables/AsyncIterables. `as` is a hybrid of `from` and `of`, except that when handed a string, it doesn't iterate the chars from the string (like `from` would), and instead works like `of`. This PR also reverts #117, so that `Iterable.from` behaves like the built-in `Array.from` again.

feat(as): Add static `as` convenience methods to wrap values as Async/Iterables

---

gulpfile.js
package.json
spec/Ix.ts
spec/asynciterable/fromnodestream-spec.ts
src/Ix.internal.ts
src/asynciterable/fromnodestream.ts

Enables the `fromNodeStream` tests.
Apparently TS enums don't minify well through closure-compiler, so I had to erase the enum and directly compare ints. Also Uglify erroneously minifies the EventEmitter method names, so I guard those by referencing via string indexers.

fix(fromnodestream): enable fromnodestream tests, fix minification problems

---

src/add/asynciterable-operators/first.ts
src/add/asynciterable-operators/last.ts
src/add/asynciterable-operators/single.ts
src/add/iterable-operators/first.ts
src/add/iterable-operators/last.ts
src/add/iterable-operators/single.ts
src/asynciterable/first.ts
src/asynciterable/last.ts
src/asynciterable/single.ts
src/iterable/first.ts
src/iterable/last.ts
src/iterable/single.ts

Since they're listed first, the user-defined typeguard types are taking precedence over the optional-predicate forms of the value-or-Promise-returning operators when no predicate is supplied. Since they downcast to a subtype of the input type, this behavior can cause the types to flow incorrectly.
Intellisense currently:
Intellisense with this PR applied:

fix(typings): Fix optional predicate typings for user-defined typeguard predicates

---

gulpfile.js
src/asynciterable/distinct.ts
src/asynciterable/except.ts
src/asynciterable/flatten.ts
src/asynciterable/intersect.ts
src/asynciterable/reverse.ts
src/asynciterable/skiplast.ts
src/asynciterable/takelast.ts
src/asynciterable/toarray.ts
src/asynciterable/union.ts
src/asynciterable/zip.ts
src/iterable/distinct.ts
src/iterable/except.ts
src/iterable/flatten.ts
src/iterable/intersect.ts
src/iterable/reverse.ts
src/iterable/skiplast.ts
src/iterable/takelast.ts
src/iterable/toarray.ts
src/iterable/union.ts
src/iterable/zip.ts

This works around (what I believe are) [typescript compiler bugs](https://github.com/Microsoft/TypeScript/issues/20299) introduced when projects are compiled without all the `--strict` mode flags on, specifically `--noImplicitAny` and `--strictNullChecks`.
We don't see these errors because we run with all the strict mode flags, enabling TS to infer more than it can when not in strict mode.
Fixes these errors caused by `strictNullChecks` being `false`:
```
ix/asynciterable/flatten.ts(19,7): error TS7030: Not all code paths return a value.
ix/asynciterable/takelast.ts(15,7): error TS7030: Not all code paths return a value.
ix/asynciterable/zip.ts(28,11): error TS7030: Not all code paths return a value.
ix/iterable/flatten.ts(19,7): error TS7030: Not all code paths return a value. …
```

Fix TS errors when used in projects with less strict compiler flags than ours

---

src/iterable/catch.ts

Minor spelling mistake, 1 letter off 😺

Minor spelling error in docs

---

src/asynciterable/concat.ts
src/asynciterable/merge.ts
src/iterable/concat.ts

Adding these three lines no longer produces the 2.7 compile errors (as seen below).
```
ERROR in [at-loader] ./node_modules/ix/add/asynciterable-operators/concat.ts:63:10
TS2556: Expected 1-6 arguments, but got 1 or more.
ERROR in [at-loader] ./node_modules/ix/add/asynciterable-operators/merge.ts:63:10
TS2556: Expected 1-6 arguments, but got 1 or more.
ERROR in [at-loader] ./node_modules/ix/add/iterable-operators/concat.ts:54:10
TS2556: Expected 1-6 arguments, but got 1 or more.
```
resolves #214

fix(compile): adding some missing exports to deal with typescript 2.7.x compat issue

---

readme.md

To keep it consistent with most of the code blocks add output to the code blocks that were missing, and also add "Next" in the output where appropriate
Adds more consistent info to the code blocks in the README file.

Add output to codeblocks in README

---

spec/asynciterable-operators/batch-spec.ts
src/Ix.ts
src/add/asynciterable-operators/batch.ts
src/asynciterable/batch.ts
src/asynciterable/index.ts

This PR adds `AsyncIterableX#batch()` that continuously collects values from the source sequence and returns another sequence of batches. It is somewhat similar to `AsyncSink`, except that it gives back all collected values at once instead of the oldest one.
I've added tests for demonstration purposes. Some edge cases are not covered yet. If this addition fits the project, I'll update them.
There are also a few ways this could be further extended:
* passing a predicate that given a batch tells whether we should suspend collecting values
* passing a custom `reduce` function that collects the batch, e.g. populating a Node.js `Buffer`, or implementing a ring buffer

Add `AsyncIterableX#batch()`

---

gulp/copy-main-task.js
gulp/package-task.js
gulp/typescript-task.js
gulp/util.js
gulpfile.js
src/Ix.dom.ts
src/Ix.node.ts
src/asynciterable/asynciterablex.ts
src/asynciterable/fromdomstream.ts
src/asynciterable/todomstream.ts

Switches the main `ix` package to include `esnext/cjs` and `esnext/esm` by default. Creates external sourcemap files instead of inline. Adds `tee`, `pipeTo`, and `pipeThrough`. Moves the node `pipe` proto override into the `asynciterablex.ts` file so it's accessible if you don't import the top-level module.

Packaging cleanup, add tee, pipeTo, pipeThrough DOM Streams methods

---

spec/asynciterable-operators/share-spec.ts
src/asynciterable/share.ts

When iterating over a `share`d AsyncIterable created from a generator function, a `break` statement effectively destroys the shared iterator making it impossible to continue iteration on it later.
This PR updates `share` operator to wrap an iterator disabling its `return` method.
The downside of this is that we won't be able to destroy a shared iterator when we want to. An alternative approach is to add a `detach` operator which simply wraps an iterator.

fix: prevent shared iterable from interrupting when breaking from loop

---

readme.md

The current README specifies the wrong import path for commonjs modules under the Iterables section. This pr just changes asynciterable to iterable
N/A

docs: fix commonjs iterable require example

---

readme.md

1. Some results of the sample are wrong. Squared of 4 is 16. not a 8.
2. mapped is not defined.
```
// L243 ~ L245
for await (let item of mapped) {
console.log(`Next: ${item}`);
}
```
n/a

docs(readme): fix wrong result of samples and typo

---

spec/asynciterable-operators/repeat-spec.ts

`repeat-spec.ts` was calling `every()` the old way, leading to an unhandled rejection. Unhandled rejections are now errors in node v15, so this was causing CI to fail.

fix(repeat-spec.ts): fix unhandled-rejection error in node v15

---

spec/iterable-operators/scan-spec.ts
spec/iterable-operators/scanright-spec.ts
spec/iterable/reduce-spec.ts
spec/iterable/reduceright-spec.ts
src/add/iterable-operators/reduce.ts
src/add/iterable-operators/reduceright.ts
src/add/iterable-operators/scan.ts
src/add/iterable-operators/scanright.ts
src/iterable/operators/scan.ts
src/iterable/operators/scanright.ts
src/iterable/reduce.ts
src/iterable/reduceright.ts

Support Array.prototype.reduce signature in Iterable scan and reduce operators again
Fix #311

fix(operators): support Array.prototype.reduce signature in Iterable scan and reduce operators again

---

src/asynciterable/operators/index.ts

`withLatestFrom` and `withAbort` were not re-exported from the barrel file. With this change, one can do:
`import { withLatestFrom } from '@reactivex/ix-ts/asynciterable/operators'`

Export withLatestFrom and withAbort operators

---

spec/asynciterable-operators/takeuntil-spec.ts
src/asynciterable/operators/takeuntil.ts

Don't wait for a value to be emitted before performing iterable completeness check
**Related issue (if exists):** #315

fix(takeUntil): complete iterable immediately (#315)

---

gulp/closure-task.js
gulp/minify-task.js
gulp/util.js

Importing multiple UMD bundles into the same page was causing the global Ix object to be replaced
each time, rather than augmented. Exporting them to distinct global objects based on the file name
causes them not to conflict.
Here's an example of something that would currently conflict. Depending on which file was imported, either `from` or `flatMap` wouldn't be available:
```html
<!DOCTYPE html>
<html><body>
<script src="/targets/esnext/umd/Ix.dom.asynciterable.js"></script>
<script src="/targets/esnext/umd/Ix.dom.asynciterable.operators.js"></script>
<script type="text/javascript">
const { from } = IxAsynciterable;
const { flatMap } = IxAsynciterableOperators;
from([0, 1, 2])
.pipe(flatMap((x) => [x + 1]))
.forEach((x) => console.log(x))
</script>
</body></html>
```

fix(umd): fix the UMD bundle export names so they don't conflict and overwrite each other

---

spec/asynciterable/aborting-spec.ts
src/asynciterable/_sleep.ts

I was having problems with using `interval` in tandem with abort signal. It caused a memory leak due to the event listeners not being cleared.
```ts
await interval(100).forEach(()=> {}, null, new AbortController().signal)
```
Running the above code would add a new event listener to the signal every 100ms.
This PR should fix the issue.

fix(Abort): Ensure removal of event listeners from AbortSignal

---

src/asynciterable/combinelatest.ts
src/asynciterable/forkjoin.ts
src/asynciterable/fromnodestream.ts
src/asynciterable/merge.ts
src/asynciterable/operators/takeuntil.ts
src/asynciterable/operators/timeout.ts
src/asynciterable/operators/withlatestfrom.ts
src/asynciterable/race.ts
src/util/safeRace.ts

I filed #322 Earlier. After some investigation it seems that the behavior observed is spec compliant. Promise.race will keep references until all promises have *settled*.
This PR introduces `safeRace` instead of `Promise.race` which is taken from [here](https://github.com/nodejs/node/issues/17469#issuecomment-685216777) and uses it for merging async iterables.

Fix memory behaviour when using itereables of differing speeds

---

docs/asynciterable/transforming.md
docs/readme.md
spec/asynciterable/buffercountortime-spec.ts
src/asynciterable/merge.ts
src/asynciterable/operators/buffercountortime.ts
src/asynciterable/operators/index.ts

After submitting a few PR's I thought it might be a good idea to share an operator that's been tremendously useful for me.
The scenario I'm dealing with is a subscription (i.e. to a message broker) that emits pretty fast. I'm handling messages from this queue in batches.
Using a plain old `bufferCount` left me in trouble because messages slow down in the evening. During the slowdown some messages would wait a long time in the buffer before being handled (sometimes not until the next day 😱)
I needed an operator that would "flush" the buffer every so often in case of slow messages.
Introducing `bufferCountOrTime` 🎉 
I changed my code from:
```ts
subscription.pipe(
bufferCount(16)
// ...
```
to 
```ts
subscription.pipe(
bufferCountOrTime(16, 1000)
// ...
```
And all is well! At worst a …

Buffer Count Or Time operator

---

.vscode/launch.json
spec/asynciterable-operators/concatmap-spec.ts
spec/asynciterable-operators/debounce-spec.ts
spec/asynciterable-operators/finalize-spec.ts
spec/asynciterable-operators/flatmap-spec.ts
spec/asynciterable-operators/timeout-spec.ts
spec/asynciterablehelpers.ts
src/asynciterable/asynciterablex.ts
src/asynciterable/operators/_flatten.ts
src/asynciterable/operators/tap.ts
src/asynciterable/operators/timeout.ts

Fixes https://github.com/ReactiveX/IxJS/issues/280

[FIX] Ensure `return` is called on AsyncIterators

---

docs/asynciterable/converting.md

NOTE: There's a subtle problem that I did not attempt to address in this PR related to module resolution. I've been away from the JS/Node ecosystem for a couple of years (though I'm a longtime fan of Ix!) and in order to run `.js` code (via Node in a terminal) copied from the docs pertaining to this PR, I found I needed to change e.g.
```js
import { fromEventPattern } from 'ix/asynciterable';
```
to
```js
import { fromEventPattern } from 'ix/asynciterable/index.js';
```
And I needed to add `"type": "module"` to `package.json` relative to the scripts I've been using for experimentation.
Alternatively, after adding `"type": "module"` to `package.json`, I could run my scripts by supplying the `--experimental-specifier-resolution=node` option in my terminal, i.e. without changing the `import` …

docs(docs/asynciterable/converting.md): Fix fromEventPattern import

---

src/asynciterable/merge.ts

Fixes return type for merge with 5 or 6 generic types, matching the other cases.
**Related issue (if exists):** -

chore(types/merge): fix return type for merge with 5, 6 args

---

src/add/asynciterable-operators/tomap.ts
src/add/iterable-operators/tomap.ts
src/asynciterable/tomap.ts
src/iterable/tomap.ts

change return type of keySelector from TElement to TKey, since keySelector returns keys, not elements
Closes: #364
change return type of keySelector to TKey. This might be a breaking change for existing code in rare cases. But then the programmer would very likely have worked around the bug this PR fixes. Feedback welcome.
#364

fix(toMap): fix return type of keySelector

---

spec/asynciterable-operators/flatmap-spec.ts
src/util/returniterator.ts

fix(flatmap): flatMap shouldn't throw when the input size is smaller than concurrent

---

src/asynciterable/operators/_flatten.ts

This change prevents us from requesting a value from the outer iterator if we are currently maxed out for concurrency on our inner iterators, This prevents a potential OOM exception where the inner iterators process at a slower rate the the outer iterator can produce.
**Related issue (if exists): #375**

Fix memory memory management for flatMap
